### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [horganke/project9#1]
Excellent use of SCSS and `provide`. I also enjoyed creative use of a helper method! There's just _one_ thing I'd like you to fix: I see some hard-tabs in the SCSS and also one in the `static_controller.rb`. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by horganke** [comment]
Taken care of I believe! Let me know if not

**Comment by chrisvfritz** [comment]
The SCSS is partly better, though I do still see quite a few hard-tabs. If you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md#global) to draw white space, you'll be able to see the hard-tabs as horizontal lines, while spaces will show up as dots, [like this](https://www.dropbox.com/s/2wzaza46t2xlrmd/Screenshot%202015-03-25%2019.45.43.png?dl=0). The static controller doesn't look like it's been touched yet.

**Comment by horganke** [comment]
Okay I see, didn't see anything changing at first in Sublime but the dots and lines helped. Check now latest commit

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
